### ISSUE TITLE
Add cmake support

### ISSUE THREAD

**Issue by 123marvin123** [andreabenini/moebius#1]
I think you should add a package for cmake, because it's really important and often used for compiling.

**Comment by andreabenini** [comment]
Thanks marvin, I'm now on the hw side (i2c packages) but you're right. I'll surely add it

**Comment by 123marvin123** [comment]
Do you compile it always yourself? I'm compiling cmake right now, maybe I can provide the binary if it finished.

**Comment by andreabenini** [comment]
Would be so cool ! :)
this project is not so big but I still have a lot of things to do, if you compile and pack it as a deb package I even give you access to this github repo with PR.

**Comment by 123marvin123** [comment]
Nice to hear, but I have no idea how to make a deb package, because I'm not really used to linux.
But I will try to search for a good tutorial on how to make a deb file, and then I will write back :)

**Comment by 123marvin123** [comment]
Ok, it compiled and is working good (took ~4 hours lol). Now I will read tutorial and tell you if I succeeded with creating a deb pkg.

**Comment by 123marvin123** [comment]
Somehow, I can't create a .deb file on my system. Do you have an idea why?

root@moebius:~# dpkg-deb --build cmake
dpkg-deb: building package `cmake' in`cmake.deb'.
find: unrecognized: -path
BusyBox v1.22.1 (2015-02-01 21:09:03 CET) multi-call binary.

Usage: find [-HL] [PATH]... [OPTIONS] [ACTIONS]

dpkg-deb: error: subprocess find returned error exit status 1

**Comment by andreabenini** [comment]
I have just created cmake for you and for who wants it. 
just apt-get update and you'll have it.

I don't have tested it (yet), just compiled and uploaded, nothing more. Give it a spin and tell me how it goes

**Comment by 123marvin123** [comment]
I've built it myself (version 3.2.1), but it seems like yours is working too. How do you make your packages, because it looks like your built cmake version is 2.8.12. Do you use a virtual machine to compile it for arm and then push it to repo, or do you build on pi?

**Comment by andreabenini** [comment]
I have a full blown cross compile toolchain on my desktop pc (Gentoo). I created a toolchain (with eglibc), imported broadcom binaries and followed the LFS and ELFS books. It takes a lot of time but I did it. I use my Pis for testing purposes but not for compiling the whole stuff, if you consider 4h for cmake you don't even imagine what it could be with gcc or opencv...

**Comment by 123marvin123** [comment]
Ok, thanks for the info. I think this issue can be closed now.
